#!/usr/bin/env python3
"""
Debug script to inspect actual grid values being generated
"""

import pandas as pd
import numpy as np
from py_tune import grid_regular

# Create the exact same grid as in Notebook 14 cell 31
grid_multi = grid_regular(
    {
        'trees': {'range': (50, 200)},
        'min_n': {'range': (2, 20)}
    },
    levels=4
)

print("=" * 60)
print("GRID VALUES GENERATED BY grid_regular()")
print("=" * 60)
print(f"\nGrid shape: {grid_multi.shape}")
print(f"\nGrid columns: {list(grid_multi.columns)}")
print(f"\nFull grid:\n{grid_multi}")
print(f"\nmin_n values: {grid_multi['min_n'].tolist()}")
print(f"\nmin_n data type: {grid_multi['min_n'].dtype}")
print(f"\nUnique min_n values: {sorted(grid_multi['min_n'].unique())}")

# Test what np.linspace actually generates
print("\n" + "=" * 60)
print("DIRECT np.linspace TEST")
print("=" * 60)
values = np.linspace(2, 20, 4)
print(f"\nnp.linspace(2, 20, 4) = {values}")
print(f"As integers: {[int(v) for v in values]}")

print("\n" + "=" * 60)
print("PROBLEM DIAGNOSTIC")
print("=" * 60)
print("\nThe grid_regular() function should generate [2, 8, 14, 20] for min_n.")
print("If sklearn is receiving 0 and 1 instead, something is modifying the values")
print("AFTER grid generation but BEFORE they reach the sklearn engine.")
